# SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

services:
  fms-zenoh-router:
    command: -c /zenoh-config.json5
    environment:
      RUST_LOG: zenoh=info
    image: eclipse/zenoh:1.0.0
    container_name: "fms-zenoh-router"
    networks:
      - "fms-backend"
      - "fms-vehicle"
    ports:
      - 7447:7447/tcp
    restart: unless-stopped
    volumes:
      - ./zenoh-config-router.json5:/zenoh-config.json5

  fms-forwarder:
    command: "zenoh -c /zenoh-config.json5"
    depends_on:
      fms-zenoh-router:
        condition: service_started
    volumes:
      - ./zenoh-config-client.json5:/zenoh-config.json5

  fms-consumer:
    command: "zenoh -c /zenoh-config.json5"
    image: "ghcr.io/eclipse-sdv-blueprints/fleet-management/fms-consumer:main"
    build:
      context: "./components"
      dockerfile: "Dockerfile.fms-consumer"
    container_name: "fms-consumer"
    cap_drop:
      - CAP_MKNOD
      - CAP_NET_RAW
      - CAP_AUDIT_WRITE
    networks:
      - "fms-backend"
    depends_on:
      influxdb:
        condition: service_healthy
      fms-zenoh-router:
        condition: service_started
    env_file:
      - "./influxdb/fms-demo.env"
    environment:
      INFLUXDB_TOKEN_FILE: "/tmp/fms-demo.token"
      RUST_LOG: "${FMS_CONSUMER_LOG_CONFIG:-info,fms_consumer=debug,influx_client=debug}"
    volumes:
      - ./zenoh-config-client.json5:/zenoh-config.json5
      - type: "volume"
        source: "influxdb-auth"
        target: "/tmp"
        read_only: true
